### ISSUE TITLE
Pre-delivery checklist

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#145]
- [ ] SSL installation
- [ ] User login timeout
- [ ] Google login SSO
- [ ] Security review: https://www.drupal.org/node/244924
- [ ] File and directory permissions review
- [ ] NodeSquirrel
- [ ] Pingdom
- [ ] Restrict /admin to IP addresses
- [ ] Security advisory RSS
- [ ] Login security module
- [ ] Security review module

```
<FilesMatch "(MAINTAINERS|INSTALL|INSTALL.mysql|CHANGELOG).txt">
  Order deny,allow
  deny from all
  Allow from 127.0.0.1  <-- your domain goes here
</FilesMatch>
<FilesMatch "(authorize|cron|install|update).php">
  Order deny,allow
  deny from all
  Allow from 127.0.0.1  <-- your domain goes here
</FilesMatch>
```

**Comment by cchristopherhowardd** [comment]
Great to see this list!

**Comment by jasloe** [comment]
Site is now served from https://

http:// will redirect automatically.

**Comment by jasloe** [comment]
Notes: 

Pingdom subscription has expired. Need to reactivate. 
Backup migrate is no longer supported. Need to write custom script.
File and dir permissions, asset compression are all set. Will implement at launch. 
Login security module and IP restriction is overkill. Will review whether this is necessary down the road.

**Comment by jasloe** [comment]
Password constraints here:

https://github.com/aarome/aarome/wiki/User-account-security

**Comment by jasloe** [comment]
Not 100% sure backup and migrate is working so I wrote this shell script. This dumps the database and files directory into an S3 bucket.

```
#!/bin/bash
BACKUPROOT="/vol0/aarome/files"
TSTAMP=$(date "+%Y.%m.%d-%H.%M.%S")
S3BUCKET="aarome-public-files"

# Logging
LOG_ROOT="/vol0/backups/aarome-public-backups/logs/dump.log"

# Dumping
mysqldump -h 10.0.2.10 -u backups --database some-database -p"some-password" > $BACKUPROOT/aarome-public-$TSTAMP.sql

# Compressing
gzip $BACKUPROOT/aarome-public-$TSTAMP.sql

# Logging
echo "$(tput setaf 3)$TSTAMP: Finished backup of database." >> "$LOG_ROOT"

# Putting
aws s3api put-object --bucket aarome-dhc-backups --key aarome-public-$TSTAMP.sql.gz --body $BACKUPROOT/aarome-public-$TSTAMP.sql.gz

# More Logging
echo "$(tput setaf 2)$TSTAMP: Moved the files from local directory to S3 bucket." >> "$LOG_ROOT"
echo "$(tput setaf 3)$TSTAMP: aarome.org backup script completed." >> "$LOG_ROOT"

# Delete files older than 15 days
find  $BACKUPROOT/*   -mtime +15   -exec rm  {}  \;
```
